permalink: /posts/:title

gems:
  - jekyll-sitemap


logo: https://avatars2.githubusercontent.com/u/6796009
name: Luca Leon Happel
url: https://quoteme.github.io/
description: A place for my thoughts
twitter: luca_happel

# Conversion
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false

# Markdown Processors
kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : 1..6
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false
  math_engine       : mathjax
  syntax_highlighter: rouge
  enable_coderay    : true
  parse_block_html  : true
