theme: jekyll-theme-minimal
description: >
    I am Luca Leon Happel, a mathematics and computer
    science student in Germany. This is my place for
    mathematics, programming and all things I deem interesting.
    <a href="https://www.paypal.me/lucahappel" target="about_blank">
    <img src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" />
    </a>
logo: https://avatars2.githubusercontent.com/u/6796009
