project:
  type: website
  resources:
    - robots.txt

website:
  site-url: "https://happel.ai/"
  title: "happel.ai"
  favicon: "favicon.png"
  description: "Website of {{< var profile.name >}}: data science, AI, high-security software and app development consulting, plus lots of math and computer science."
  open-graph:
    image: https://avatars2.githubusercontent.com/u/6796009
    description: "Website of Luca Happel: data science, AI, high-security software and app development consulting, plus lots of math and computer science."
  twitter-card:
    image: https://avatars2.githubusercontent.com/u/6796009
    description: "Website of Luca Happel: data science, AI, high-security software and app development consulting, plus lots of math and computer science."
  google-analytics: "G-TS8KXZ05HZ"

  draft-mode: unlinked
  navbar:
    title: false
    logo:
      light:
        path: assets/happel-ai-logo.svg
        alt: "happel.ai"
      dark:
        path: assets/happel-ai-logo-dark.svg
        alt: "happel.ai"
    logo-href: index.qmd
    left:
      - text: Blog
        icon: journal-text
        href: blog.qmd
    tools:
      - icon: github
        aria-label: GitHub
        href: https://github.com/Quoteme/
      - icon: linkedin
        aria-label: Linkedin
        href: https://www.linkedin.com/in/lucahappel/
      - icon: instagram
        aria-label: Instagram
        href: https://www.instagram.com/lucaleonhappel/
      - icon: reddit
        aria-label: Reddit
        href: https://www.reddit.com/user/lalelul
    right:
      - text: Services
        icon: briefcase
        href: /#services
      - text: FAQ
        icon: question-circle
        href: /#faq
      - text: Contact
        icon: envelope
        href: /#contact
  page-footer:
    center:
      - text: "Impressum"
        href: "impressum.qmd"
      - text: "Datenschutz"
        href: "datenschutz.qmd"
format:
  html:
    include-in-header:
      - file: "macros.html"
    css: styles.css
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    respect-user-color-scheme: true
    filters:
      - callouty-theorem
