project:
  type: website

website:
  site-url: "https://happel.ai/"
  title: "{{< var website.title >}}"
  favicon: "favicon.png"
  description: "Personal website of {{< var profile.name >}}, including lots of math and computer science."
  open-graph:
    image: https://avatars2.githubusercontent.com/u/6796009
    description: Luca Happel's personal website, including lots of math and computer science.
  twitter-card:
    image: https://avatars2.githubusercontent.com/u/6796009
    description: Luca Happel's personal website, including lots of math and computer science.
  google-analytics: "G-TS8KXZ05HZ"

  navbar:
    right:
      - about.qmd
      - projects.qmd
      - icon: github
        aria-label: GitHub
        href: https://github.com/Quoteme/
      - icon: linkedin
        aria-label: Linkedin
        href: https://www.linkedin.com/in/lucahappel/
      - icon: instagram
        aria-label: Instagram
        href: https://www.instagram.com/lucaleonhappel/
      - icon: reddit
        aria-label: Reddit
        href: https://www.reddit.com/user/lalelul
  page-footer:
    center:
      - text: "Impressum"
        href: "impressum.qmd"
      - text: "Datenschutz"
        href: "datenschutz.qmd"
format:
  html:
    include-in-header:
      - file: "macros.html"
    css: styles.css
    theme:
      light: cosmo
    filters:
      - callouty-theorem
filters:
  - auto-dark
