---
title: "$\\ell^2$-Invariants"
author: "Luca Leon Happel"
date: "2024-02-04"
date-modified: "2024-02-05"
categories: ["mathematics", "topology", "algebra", "group theory", "ring theory", "measure theory", "functional analysis", "differential geometry", "differential topology", "algebraic topology"]
bibliography: references.bib
format:
    html:
        code-fold: true
        code-summary: "Show the code"
---

> <span style="color: red">__WARNING__: This is a work in progress. I am currently writing this article and it is not finished yet. I will update it regularly and remove this warning once it is finished.</span>

## Introduction

This semester (WiSe 2023/24) I took a course about $\ell^2$-Invariants[see @WEBSITE:1] at the University of D端sseldorf. As a reminder, $\ell^2$ is the [Hibert space of __square-summable__ sequences](https://en.wikipedia.org/wiki/Lp_space#The_p-norm_in_finite_dimensions) of complex numbers. Meaning, a sequence $(a_n\in\mathbb{C})_{n=0}^\infty$ is in $\ell^2$ if and only if $\sum_{n=0}^\infty |a_n|^2 < \infty$. By defining an inner product on $\ell^2$ as $\langle a, b \rangle = \sum_{n=0}^\infty a_n \overline{b_n}$, we make $\ell^2$ to a complete complex inner product space, i.e. a Hilbert space.

For context, this course was part of my master's degree in mathematics and it was the culmination of a series of courses about __Algebraic Topology__, which I attended for the past two and a half years.
Previous courses concentrated primarily on the basics of algebraic topology, such as homology and cohomology, and their applications to the classification of manifolds and the computation of homotopy groups and cohomology rings.

The tools in the form of algebraic structures and theorems that we learned in these coureses, like homology, work well with finite CW-complexes and their finite coverings, after all we are just dealing with finitely generated modules in these cases and concepts like determinants and betti numbers are well defined. However, when we want to study infinite CW-complexes, we need to use more sophisticated tools, such as $\ell^2$-Invariants, to understand the topology of these spaces.
Something interesting happens, when we look at covering spaces of finite CW-complexes. By the Galois correspondence, we can associate a covering space $\bar X$ with a subgroup $H$ of the fundamental group $G$ of a base space $X$.[see @Hatcher1.38, Proposition 1.38] Now, we have a group action of $G$ on $\bar X$ and this added structure allows us to define the $\ell^2$ betti numbers $b_i^{(2)}(H \curvearrowright \bar X)$, $\ell^2$ homology groups $H_i^{(2)}(H \curvearrowright \bar X)$ and much more.

Let us build some intuition before we proceed though. Consider the base space $X=S^1$, and a $d$ sheeted covering $\bar X_d$. The fundamental group of $X$ is $\mathbb{Z}$ and the fundamental group of $\bar X_d$ is $\mathbb{Z}/d\mathbb{Z}$. An early result in the study of $\ell^2$-Invariants is that for $d$-sheeted coverings $\bar X_d \to X$, the $\ell^2$-betti numbers of $\bar X_d$ are $b_i^{(2)}(\mathbb{Z}/d\mathbb{Z}\curvearrowright\bar X_d) = b_i(\bar X_d) / |\mathbb{Z}/d\mathbb{Z}| = b_i(\bar X_d) / d$. This is quite astounding, as betti numbers are commonly seen as "counting the number of $i$-dimensional holes" in a space, but here we see that the $\ell^2$-betti numbers are not integers, but rational numbers. So, geometrically, what does it mean for a space to have "one third of a hole"? Let us investigate for the case $d=3$.

```{python}
# 3d plotly plot of a a circle and a 3-sheeted covering right next to it
import plotly.graph_objects as go
import numpy as np
# S^1
def s1()->(np.ndarray, np.ndarray, np.ndarray):
	theta = np.linspace(0, 2*np.pi, 100)
	x = np.cos(theta)
	y = np.sin(theta)
	z = np.zeros(100)
	return x, y, z
# 3-sheeted covering
def covering(sheets: int, handlestart: float = 1/8, subsections=100):
	theta = np.linspace(0, (sheets-handlestart)*2*np.pi, subsections)
	x = np.cos(theta)
	y = np.sin(theta)
	z = theta/(2*np.pi)
	# Add a small handle from (1,0,0) to (1,0,`sheets`) in a small bow.
	# This handle is just here to show that this covering is still homeomorphic to S^1.
	# The preimages of (1,0,0) therefor would still be a discrete set of `sheets` points, not a line.
	x = np.append(x, ( lambda v : (1-v**6)/10 )(np.linspace(-1,1, subsections)) + np.cos(np.linspace((sheets-handlestart)*2*np.pi, sheets*2*np.pi, subsections)))
	y = np.append(y, ( lambda v : (1-v**6)/10 )(np.linspace(-1,1, subsections)) + np.sin(np.linspace((sheets-handlestart)*2*np.pi, sheets*2*np.pi, subsections)))
	z = np.append(z, ( lambda v : (1-np.arctan(10*v)/np.arctan(10))*(sheets-handlestart)/2 )( np.linspace(-1, 1, subsections) ))
	return x,y,z
# draw the plot
fig = go.Figure()
fig.add_trace((lambda v: go.Scatter3d(x=v[0], y=v[1], z=v[2], mode='lines', name='S^1'))(s1()))
fig.add_trace((lambda v: go.Scatter3d(x=v[0], y=v[1], z=v[2], mode='lines', name=f'{3}-sheeted covering'))(covering(3)))
fig.show()
```

It is clear, that the betti numbers of the circle $S^1$ are $b_0(S^1) = 1$ and $b_1(S^1) = 1$.
The same is the case for any $n$-sheeted covering. In particular, we have $b_0(\bar X_3) = 1$ and $b_1(\bar X_3) = 1$. 
When we take a look at the $\ell^2$-betti numbers, we must take into account the action of the __deck transformation group__[see @Hatcher.DeckTransform]
$\text{Deck}(p) = \mathbb{Z}/3\mathbb{Z}$ on $\bar X_3$, where $p: \bar X_d \to X$ is the canonical projection.

```{python}
import plotly.express as px
import numpy as np
import pandas as pd

# Function to generate circle coordinates for a given t of rotation around the x-axis
def get_frame(t):
	x,y,z = covering(3)
	x = (1-t)*x+t*x/np.hypot(x,y)
	y = (1-t)*y+t*y/np.hypot(x,y)
	z = z*(1-t)
	return x, y, z

# Generate data for each frame
ts = np.linspace(0, 1, 20)
df = pd.DataFrame()

for t in ts:
	x, y, z = get_frame(t)
	temp_df = pd.DataFrame({'x': x, 'y': y, 'z': z, 't': t})
	df = pd.concat([df, temp_df])

# Initial plot using Plotly Express
fig = px.line_3d(df, x='x', y='y', z='z', animation_frame='t')

# Fixing the axis ranges
fig.update_layout(
	scene=dict(
		xaxis=dict(range=[-1.3,1.3], autorange=False),
		yaxis=dict(range=[-1.3,1.3], autorange=False),
		zaxis=dict(range=[0,3], autorange=False),
		aspectmode='cube',  # This ensures equal aspect ratio for all axes
	),
	title="Homotopy between id and p",
	updatemenus=[{
		"buttons": [
			{
				"args": [None, {"frame": {"duration": 50, "redraw": True}, "fromcurrent": True}],
				"label": "Play",
				"method": "animate"
			},
			{
				"args": [[None], {"frame": {"duration": 0, "redraw": True}, "mode": "immediate", "transition": {"duration": 0}}],
				"label": "Pause",
				"method": "animate"
			}
		],
		"direction": "left",
		"pad": {"r": 10, "t": 87},
		"showactive": False,
		"type": "buttons",
		"x": 0.1,
		"xanchor": "right",
		"y": 0,
		"yanchor": "top"
	}],
	sliders=[{
		"steps": [{"args": [[f"{t}"], {"frame": {"duration": 50, "redraw": True}, "mode": "immediate"}], 
				   "label": f"{t}", "method": "animate"} for t in ts],
	}]
)
# Show figure
fig.show()
```

Maybe it is already somewhat obvious, that there is a canonical [group action](https://en.wikipedia.org/wiki/Group_action) from $\mathbb{Z}/3\mathbb{Z}$ on $\bar X_3$. This action, the deck transformation, permutes the three preimages of each point in $S^1$ using [Cayley's theorem](https://en.wikipedia.org/wiki/Cayley%27s_theorem). The result of applying the deck transformation to $\bar X_3$ therefore is a 3-sheeted covering of $S^1$ again and is an isomorphism of covering spaces from $\bar X_3$ to $\bar X_3$. As an example, let us consider some point $x$ on $\bar X_3$. $\text{Deck}(p) \cong \mathbb{Z}/3\mathbb{Z} \cong \langle g | g^3 = 0\rangle$ acts on $x$ by $g.x = x + 1$, if $x$ is not in the topmost sheet, otherwise it pushes $x$ down to the bottom sheet, assuming we embed $\bar X_3$ into $\mathbb{R}^3$ in the obvious way. In the following plot, we can see what happens to both a single point and the whole covering space under the action of the deck transformation. From left to right, we apply $g$ not at all, once and then twice.

```{python}
from plotly.subplots import make_subplots
# the individual point we want to track under the action of the deck transformation
angle = np.pi*7/8
point = ( 
	np.cos(angle),
	np.sin(angle),
	angle/(2*np.pi)
 )
# group action. Because Z/3Z is cyclic, we only need to define the generator
g = lambda v: (v[0],v[1],v[2]+1 if v[2] < 2 else 0)

# covering [0]
fig = make_subplots(rows=1, cols=3, specs=[[{'type': 'scene'}, {'type': 'scene'}, {'type': 'scene'}]])
fig.add_trace((lambda v: go.Scatter3d(x=v[0], y=v[1], z=v[2], mode='lines', name='[0]'))(covering(3)), row=1, col=1)
# add a little red dot to show what happens to one individual point
fig.add_trace(go.Scatter3d(x=[point[0]], y=[point[1]], z=[point[2]], mode='markers', name="x", marker=dict(size=5, color='red')), row=1, col=1)

# covering [1]
fig.add_trace((lambda v: go.Scatter3d(x=v[0], y=v[1], z=v[2], mode='lines', name='[1]'))(covering(3, 0, 100)), row=1, col=2)
fig.add_trace(go.Scatter3d(x=[g(point)[0]], y=[g(point)[1]], z=[g(point)[2]], mode='markers', name="g.x", marker=dict(size=5, color='red')), row=1, col=2)

# covering [2]
fig.add_trace((lambda v: go.Scatter3d(x=v[0], y=v[1], z=v[2], mode='lines', name='[2]'))(covering(3, 1/8, 100)), row=1, col=3)
fig.add_trace(go.Scatter3d(x=[g(g(point))[0]], y=[g(g(point))[1]], z=[g(g(point))[2]], mode='markers', name="g.g.x", marker=dict(size=5, color='red')), row=1, col=3)


# legend
fig.update_layout(
	title="Group action of the cyclic group with three elements on our covering space",
)
fig.show()
```

It seems that $\ell^2$-betti numbers somehow measure "how much each symmetry contributes to the betti-number", but we still need to make this precise. In this example however, there are three symmetries, $b_1(X_3) = 1$ and $b_1(\mathbb{Z}/3\mathbb{Z}\curvearrowright X_3) = 1/3$, so our intuition kinda makes sense.

### Futher Motivation

One of the main goals in this lecture was for us to reach L端ck's theorem:

> __L端ck's theorem__: _Let $X$ be a connected, compact CW-complex whose fundamental group $G=\pi_1(X)$ is residually finite. Then for every residual chain $(G_i)$ in $G$ and every $n\ge 0$ we have_
> $$\lim_{i\to\infty} \frac{b_n^{(2)}(\bar X_i)}{[G:G_i]} = b_n^{(2)}(G\curvearrowright \tilde X)$$
> _where $\bar X_i \to X$ is the covering space associated with $G_i$ and $\tilde X$ is the universal covering space of $X$._

For clearance, the definition of a residual chain is as follows:

> __Definition 1.1__: _A sequence $G=G_0 \ge G_1 \ge G_2 \ge \dots$ of subgroups of a group $G$ is called a __residual chain__ if for each $i\ge 0$ the index $[G:G_i]$ is finite and the intersection $\bigcap_{i\ge 0} G_i = \{1\}$_.

So a simple and fitting example of a residual chain would be the sequence $G_i = \mathbb{Z}/2^i\mathbb{Z}$ for $i\ge 1$ and $G_0 = \mathbb{Z}$ in the case of $G=\mathbb{Z}$, as we had before with $S^1$ and its universal covering space $\tilde X = \mathbb{R}$. By plugging in L端ck's theorem, we get:

$$
\begin{align*}
& \lim_{i\to\infty} \frac{b_n^{(2)}(\bar X_i)}{[G:G_i]} &= b_n^{(2)}(G\curvearrowright \tilde X) \\
\Leftrightarrow& \lim_{i\to\infty} \frac{b_n^{(2)}(\bar X_i)}{2^i} &= b_n^{(2)}(\mathbb{Z}\curvearrowright \mathbb{R}) \\
\Leftrightarrow& \lim_{i\to\infty} \frac{\frac{1}{2^i}}{2^i} &= b_n^{(2)}(\mathbb{Z}\curvearrowright \mathbb{R}) \\
\Leftrightarrow& 0
\end{align*}
$$

In fact, we can generalize this to $b_n^{(2)}(\tilde { \mathbb{T}^k }) = 0$, where $\mathbb{T}^k$ is the $k$-dimensional torus and therefor $\tilde { \mathbb{T}^k } \cong \mathbb{R}^k$, which is in stark contrast to the usual betti numbers $b_n(\tilde { \mathbb{T}^k }) = \binom{k}{n}$.

## Construction of $\ell^2$-Cell Complexes



[^1]: The course was held by [Jun.-Prof. Dr. Holger Kammeyer](https://www.math.uni-duesseldorf.de/~kammeyer/).
[^2]: Allen Hatcher, "Algebraic Topology", Cambridge University Press, 2002. [Link to the book](https://pi.math.cornell.edu/~hatcher/AT/ATpage.html)
[^2]: Allen Hatcher, "Algebraic Topology", Cambridge University Press, 2002. [Link to the book](https://pi.math.cornell.edu/~hatcher/AT/ATpage.html)